import localFont from 'next/font/local'
import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { Header } from '@/module/Header/Header';

const roboto = localFont({
  src: [
    {
      path: './fonts/Roboto-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Roboto-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Roboto-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <QueryProvider>
          <Header />
          <main>
            {children}
          </main>

          {/* footer */}
        </QueryProvider>
      </body>
    </html>
  );
}
